const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch();
 try{
  const base=process.env.ERP_TEST_URL;
  const page=await browser.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/admin');
  await page.locator('[name=name]').fill('Portal Admin');
  await page.locator('[name=username]').fill('portal-admin');
  await page.locator('[name=password]').fill('Portal-test-password-123');
  await page.locator('#login-form button').click();
  await page.locator('nav a[href="#users"]').waitFor();
  assert.equal(new URL(page.url()).pathname,'/admin');
  assert.equal(await page.locator('#portal-name').textContent(),'Admin panel');
  assert.equal(await page.locator('#portal-navigation [aria-current=page]').getAttribute('href'),'/admin');
  await page.locator('#portal-navigation a[href="/user"]').click();
  await page.getByRole('heading',{name:'Switch to User portal',exact:true}).waitFor();
  assert.equal(new URL(page.url()).pathname,'/user');assert(await page.locator('aside').isHidden());
  await page.getByRole('link',{name:'Return to Admin panel',exact:true}).click();
  await page.locator('nav a[href="#users"]').waitFor();
  const created=await page.evaluate(async()=>{const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'portal-store',name:'Portal Store',role:'Store',password:'Portal-test-password-123'})});return r.status});assert.equal(created,200);
  await page.locator('#portal-navigation a[href="/user"]').click();
  await page.locator('#confirm-portal-switch').click();
  await page.getByRole('heading',{name:'User sign in',exact:true}).waitFor();
  assert.equal(await page.locator('#login-form [name=username]').inputValue(),'');
  assert.equal(await page.evaluate(async()=> (await fetch('/api/state')).status),401);
  await page.goto(base+'/admin');
  await page.locator('[name=username]').fill('portal-store');
  await page.locator('[name=password]').fill('Portal-test-password-123');
  await page.locator('#login-form button').click();
  await page.getByText('Use the Admin panel for Admin accounts and the User portal for department accounts.',{exact:true}).waitFor();
  await page.goto(base+'/user');
  await page.locator('[name=username]').fill('portal-store');
  await page.locator('[name=password]').fill('Portal-test-password-123');
  await page.locator('#login-form button').click();
  await page.locator('nav a[href="#inventory"]').waitFor();
  assert.equal(await page.locator('nav a[href="#users"]').count(),0);
  const bootstrap=[];page.on('request',r=>{if(r.url().includes('/api/'))bootstrap.push(new URL(r.url()).pathname)});
  await page.reload();await page.locator('nav a[href="#inventory"]').waitFor();
  assert.deepEqual(bootstrap,['/api/bootstrap']);
  assert.equal(await page.locator('#portal-name').textContent(),'User portal');
  assert.equal(await page.locator('#portal-navigation [aria-current=page]').getAttribute('href'),'/user');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/portal-user-mobile.png',fullPage:true});
  assert(await page.locator('#portal-navigation a[href="/admin"]').isVisible());
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#portal-navigation a[href="/admin"]').click();
  await page.getByRole('heading',{name:'Switch to Admin panel',exact:true}).waitFor();
  await page.screenshot({path:'test-results/portal-switch-mobile.png',fullPage:true});
  assert(await page.locator('aside').isHidden());
  assert.equal(await page.evaluate(async()=> (await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status),403);
  await page.locator('#confirm-portal-switch').click();
  await page.getByRole('heading',{name:'Admin sign in',exact:true}).waitFor();
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'test-results/portal-admin-login.png',fullPage:true});
  const bad=await browser.newPage();
  await bad.route('**/api/bootstrap',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"unavailable"}'}));
  await bad.goto(base+'/admin');await bad.getByText('Workspace unavailable',{exact:true}).waitFor();
  assert(await bad.locator('#retry-connection').isVisible());assert(await bad.locator('aside').isHidden());
  await bad.unroute('**/api/bootstrap');await bad.locator('#retry-connection').click();await bad.locator('#login-form').waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: portal tabs, explicit account switching in both directions, mobile navigation, role restrictions, one-request bootstrap, database-error screen and retry.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
